import React from 'react'

export const Alimentos = {
    Cereales: [
        'Arroz cocido 3/4 taza (100g)',
        'Arroz crudo 1/4 taza (40g)',
        'Fideos cocidos 3/4 taza (110g)',
        'Fideos crudo 1/2 taza (40g)',
        'Papa 1 unidad regular (150g)',
        'Quinoa cocida 3/4 taza (100gr)',
        'Quinoa cruda 1/4 taza (40gr)',
        'Cuscús cocido: 3/4 taza (100gr)',
        'Cuscús crudo: 1/2 taza (40gr)',
        'Choclo cocido 1 taza (160gr)',
        'Chuchoca cruda 1/4 taza (40gr)',
        'Harina tostada 1/4 taza (40gr)',
        'Pan hallulla 1/2 unidad (50gr)',
        'Pan marraqueta 1/2 unidad (50gr)',
        'Pan molde 2 rebanadas (50gr)',
        'Pan de masa madre 1/2 unidad (50gr)',
        'Avena 1/2 taza (40gr)',
        'Granola 1/2 taza (40gr)',
        'Galletas de soda 8 unidades (40gr)',
        'Galletas de agua 8 unidades (40gr)',
        'Sémola cruda 1/4 taza (40gr)',
        'Chuño crudo 1/4 taza (40gr)',
        'Maicena cruda 1/4 taza (30gr)',
    ],
    VerdurasCG: [
        'Acelga cocida 1/2 taza (110gr)',
        'Brócoli 1 taza (100gr)',
        'Repollitos de bruselas 1/2 taza (100gr)',
        'Coliflor 1 taza (110gr)',
        'Alcachofa 1 unidad chica (50gr)',
        'Champiñones cocidos 3/4 taza (100gr)',
        'Zanahoria cruda 1 taza (50gr)',
        'Espinaca cocida 1/2 taza (130gr)',
        'Zapallo italiano cocido 1 taza (150gr)',
        'Tomate 1 unidad mediana (120gr)',
        'Cebolla cruda 3/4 taza (60gr)',
        'Berenjena cocida 1/2 taza (100gr)',
        'Betarraga cocida 1/2 taza (90gr)',
        'Espárragos cocidos 5 unidades (100gr)',
        'Porotos verdes cocidos 3/4 taza (70gr)',
        'Zapallo cocido 1/2 taza (70gr)',
    ],
    VerdurasLC: [
        'Achicoria 1 taza (50gr)',
        'Apio 1 taza (70gr)',
        'Lechuga 1 taza (50gr)',
        'Repollo 1 taza (50gr)',
        'Repollo morado 1 taza (50gr)',
        'Endivia 1 taza (50gr)',
        'Dientes de ajo 8 unidades',
        'Pimentón 1/2 taza (60gr)',
        'Chochayuyo 2 ramas de 25x4cm (25gr)',
        'Espinaca cruda 1 taza (50gr)',
        'Acelga cruda 1 taza (50gr)',
        'Pepino 1 taza (100gr)',
        'Zapallo italiano crudo 1 taza (100gr)',
        'Rabanitos 5 unidades (50gr)',
    ],
    Frutas: [
        'Manzana 1 unidad chica (100gr)',
        'Durazno 1 unidad regular (130gr)',
        'Palta 1 1/2 cucharada (40gr)',
        'Frutillas 1 taza (200gr)',
        'Plátano 1/2 unidad (60gr)',
        'Sandía 1 taza (200gr)',
        'Melón 1 taza (180gr)',
        'Ciruelas 3 unidades (110gr)',
        'Higos frescos 2 unidades (80gr)',
        'Moras 1/2 taza (120gr)',
        'Papaya 3 unidades (400gr)',
        'Piña 1 rodela de 20x2cm (120gr)',
        'Cerezas 15 unidades (90gr)',
        'Damascos 3 unidades (120gr)',
        'Kiwi 2 unidades chicas (100gr)',
        'Naranja 1 unidad regular (120gr)',
        'Uvas 10 unidades (90gr)',
        'Pera 1 unidad chica (100gr)',
        'Chirimoya 1/4 unidad (90gr)',
        'Frambuesas 1 taza (130gr)',
        'Membrillo 1 unidad chica (100gr)',
        'Caqui 1 unidad chica (90gr)',
        'Níspero 7 unidades (120gr)',
        'Pepino dulce 1 unidad grande (240gr)',
    ],
    ProteinaAnimalAG: [
        'Atún en aceite 1/3 taza (50gr)',
        'Jurel en aceite 1/3 taza (50gr)',
        'Sardinas en aceite 1/3 taza (50gr)',
        'Choritos en aceite 14 unidades (60gr)',
        'Mortadela 3 tajadas (60gr)',
        'Guachalomo trozo de 6x6x1 cm (50gr)',
        'Lomo vetado trozo de 6x6x1 cm (50gr)',
        'Plateada trozo de 6x6x1 cm (50gr)',
        'Chuleta de cordero trozo de 6x6x1 cm (50gr)',
        'Chuleta de cerdo trozo de 6x6x1 cm (50gr)',
        'Hígado cocido trozo de 6x6x2 cm (60gr)',
        '**Jamón 1 tajada (40gr)',
        '**Longaniza 1 rodela de 4 cm (45gr)',
        '**Salame 1 tajada (20gr)',
        '**Prieta 1 unidad de 4 cm (100gr)',
        '**Vienesa 1 unidad (40gr)',
        '**Vienesa pavo 1 unidad (40gr)',
        '**Carnes ultra procesadas, carcinogénicas',
    ],
    ProteinaAnimalBG: [
        'Asiento picana trozo de 6x6x1 cm (50gr)',
        'Filete trozo de 6x6x1 cm (50gr)',
        'Lomo liso trozo de 6x6x1 cm (50gr)',
        'Pollo ganso trozo de 6x6x1 cm (50gr)',
        'Posta negra trozo de 6x6x1 cm (50gr)',
        'Posta rosada trozo de 6x6x1 cm (50gr)',
        'Cordero pulpa trozo de 6x6x1 cm (50gr)',
        'Cerdo filete trozo de 6x6x1 cm (50gr)',
        'Cerdo pulpa trozo de 6x6x1 cm (50gr)',
        'Pollo pechuga trozo de 6x6x1 cm (50gr)',
        'Pollo pierna trozo de 6x6x1 cm (50gr)',
        'Pavo pierna trozo de 6x6x1 cm (50gr)',
        'Jamón de pavo 1 tajada (50gr)',
        'Huevo 1 unidad (50gr)',
        'Huevo de codorniz 2 unidades (25gr)',
        'Atún en agua 1/3 taza o 1/2 lata (60gr)',
        'Jurel trozo de 10x6x1 cm (80gr)',
        'Merluza trozo de 10x6x1 cm (80gr)',
        'Reineta trozo 10x6x1 cm (80gr)',
        'Choritos 6 unidades (60gr)',
        'Jaiva 1/3 taza (60gr)',
        'Almejas 6 unidades (60gr)',
        'Piure 6 lenguas (100gr)',
        'Loco 1 unidad chica (60gr)',
    ],
    ProteinaVegetalAP: [
        'Poroto cocido 3/4 taza (100gr)',
        'Garbanzo cocido 3/4 taza (130gr)',
        'Lentejas cocidas 3/4 taza (140gr)',
        'Carne de soya cocida 3/4 taza (100gr)',
        'Hamburguesa vegetal 1/2 U (50gr)',
        'Porotos crudos 1/4 taza (50gr)',
        'Garbanzo crudo 1/4 taza (50gr)',
        'Lenteja cruda 1/4 taza (50gr)',
        'Carne de soya seca 1/4 taza (30gr)',
    ],
    ProteinaVegetalBP: [
        'Tofu 1 rebanada de 3cm (70gr)',
        'Crema de maní 1 cdta (25gr)',
        'Hummus 2 cdtas (30gr)',
    ],
    LacteosAltos: [
        'Leche fluida entera 1 taza (200gr)',
        'Yogurt natural 1 unidad (150gr)',
        'Queso chanco o gauda 1/2 tajada laminada (20gr)',
        'Queso parmesano 1/2 tajada (15gr)',
        'Queso untable 2 cucharadas (25gr)',
        'Queso crema 3 cucharadas (18gr)',
        'Queso suizo 1/2 tajada (20gr)',
        'Leche cruda de vaca 1 taza (200gr)',
        'Leche en polvo 26% grasa 2 cdas colmadas o 3 cdas rasas (20gr)',
        'Queso chedar 1/2 tajada (20gr)',
        'Queso de cabra 1/2 tajada (25gr)',
        'Queso holandés 1/2 tajada (20gr)',
    ],
    LacteosMedios: [
        'Leche en polvo 18% grasa 2 cdas colmadas o 3 cdas rasas (20gr)',
        'Leche fluida saborizada 1 taza (200gr)',
        'Yogurt batido light 1 unidad (150gr)',
        'Leche en polvo 12% grasa 2 cdas colmadas o 3 cdas rasas (20gr)',
        'Quesillo rodela de 3 cm (60gr)',
    ],
    LacteosBajos: [
        'Leche fluida descremada 1 taza (200gr)',
        'Leche en polvo descremada 2 cdas colmadas o 3 cdas rasas (20gr)',
    ],
    Lipidos: [
        'Almendras 26 unidades (25gr)',
        'Avellana 50 unidades (30gr)',
        'Maní 30 unidades o 1 puñado (30gr)',
        'Nuez 5 unidades (25gr)',
        'Pistacho 40 unidades (30gr)',
        'Aceituna 11 unidades (115gr)',
        'Palta 3 cucharadas o 1/2 unidad(90gr)',
    ],
    Grasas: [
        'Aceite de maravilla 4 cdtas (20gr)',
        'Aceite de maíz 4 cdtas (20gr)',
        'Aceite de soja 4 cdtas (20gr)',
        'Aceite de oliva 4 cdtas (20gr)',
        'Aceite de colza 4 cdtas (20gr)',
        'Aceite de canola 4 cdtas (20gr)',
        'Manteca 2 cdas (20gr)',
        'Mantequilla 4 cdtas (24gr)',
        'Margarina 4 cdtas (24gr)',
        'Margarina diet 4 cdtas (30gr)',
        'Mayonesa 1 cda (28gr)',
        'Crema nestle 4 cdtas (70gr)',
        'Crema chantilly 4 cdas (50gr)',
        'Tocino 1 1/2 tajadas (30gr)',
        'Pate 2 cdas (40gr)',
    ],
    Azucar: [
        'Azúcar 1 cdta (5gr)',
        'Miel de abeja 1 cdta (6gr)',
        'Miel de palma 1 cdta (6gr)',
        'Mermeladas 1 cdta (10gr)',
        'Membrillo dulce 1 cdta (10gr)',
        'Manjar 1 cdta (10gr)',
        'Jalea en polvo 1 porción reg (5gr)',
        'Jugo 1 cdta (5gr)',
    ],
    AlcoholAlto: [
        'Licor de café 1/3 vaso (40gr)',
        'Licor de menta 1/3 vaso (40gr)',
    ],
    AlcoholMedio: [
        'Champaña 1 vaso (180gr)',
        'Vino tinto 1 vaso (180gr)',
        'Vino blanco 1 vaso (180gr)',
        'Cerveza 300cc (300gr)',
    ],
    AlcoholSin: [
        'Martini 1/2 vaso (60gr)',
        'Pisco 1/2 vaso (60gr)',
        'Whisky 1/3 vaso (50gr)',
        'Ron 1/3 vaso (50gr)',
        'Vodka 1/3 vaso (50gr)',
    ]
};